### ISSUE TITLE
 Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by keyescgm** [bytedance/btrace#105]
成功编译，通过命令java -jar rhea-trace-processor-2.0.0.jar -a xxx -t 10 -o output.pb -r sched -fullClassName
启动后，报错内容如下：
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
        at java.base/java.util.Objects.checkIndex(Objects.java:385)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)

![image](https://github.com/bytedance/btrace/assets/9543572/3b331274-5fb9-4709-be2b-6d8b4f828f57)

plugin：com.android.tools.build:gradle:4.2.2
gradle：gradle-6.7.1
kotlin_version：1.7.0

**Comment by mzule** [comment]
这个问题应该是你没有插入任何的桩，可以配置下traceFilterFilePath里面加入-allowpackage来配置可插桩的包名。
