### ISSUE TITLE
工程接入后运行报错Unexpected end of file from server

### ISSUE THREAD

**Issue by LiuHongtao** [bytedance/btrace#133]
### 主工程配置、执行命令及报错：

* 配置

```
rheaTrace {
    compilation {
        traceFilterFilePath = "${project.rootDir}/trace-filter/traceFilter.txt"
        needPackageWithMethodMap = true
        applyMethodMappingFilePath = ''
    }
}
```

* 执行命令

`java -jar rhea-trace-processor-2.0.0.jar -a **隐藏** -t 8 -r rhea.all sched idle -fullClassName -debug`

* 报错

```
07-10 16:21:28.086 D RheaTrace : Broadcast completed: result=0
07-10 16:21:28.087 D RheaTrace : Run adb forward tcp:8004 tcp:8004
07-10 16:21:28.121 D RheaTrace : 8004
07-10 16:21:28.189   RheaTrace : MaxAppTraceBufferSize usage 32/500000000 (0%)
Exception in thread "main" java.net.SocketException: Unexpected end of file from server
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:896)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:723)
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:893)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:723)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1615)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/java.net.URL.openStream(URL.java:1165)
	at org.apache.commons.io.IOUtils.toString(IOUtils.java:2953)
	at com.bytedance.rheatrace.processor.Adb$Http.get(Adb.java:164)
	at com.bytedance.rheatrace.processor.core.Mapping.selectMapping(Mapping.java:47)
	at com.bytedance.rheatrace.processor.core.Mapping.loadMapping(Mapping.java:79)
	at com.bytedance.rheatrace.processor.core.Mapping.get(Mapping.java:36)
	at com.bytedance.rheatrace.processor.core.AppTraceProcessor.processBinary(AppTraceProcessor.java:145)
	at com.bytedance.rheatrace.processor.core.AppTraceProcessor.getBinaryTrace(AppTraceProcessor.java:50)
	at com.bytedance.rheatrace.processor.core.AbstractTraceGenerator.getAppTraceFrames(AbstractTraceGenerator.java:39)
	at com.bytedance.rheatrace.processor.core.AbstractTraceGenerator.generate(AbstractTraceGenerator.java:32)
	at com.bytedance.rheatrace.processor.perfetto.PerfettoCapture.process(PerfettoCapture.java:95)
	at com.bytedance.rheatrace.processor.Main.main(Main.java:108)
```

**Comment by caelanyang** [comment]
这个错误最终是怎么解决的呀
