### ISSUE TITLE
windows环境 rhea-trace-processor.jar运行报错 "Thread-1" com.bytedance.rheatrace.processor.core.TraceError: Perfetto return with bad code -1073741515

### ISSUE THREAD

**Issue by weimingzeng** [bytedance/btrace#141]
系统版本：windows11
java版本：11.0.23
python版本：Python 3.3.5
运行机型：oppo
感觉是环境问题，求帮忙看看
C:\Users\xx\project\tools>java -jar rhea-trace-processor.jar -a xxx -t 5 -o output.pb -r rhea.all sched -fullClassName
10-15 16:51:19.221 I RheaTrace : workspace clear: C:\Users\xxx\project\tools\rheatrace.workspace
10-15 16:51:21.056 I RheaTrace : os version is 34. default capture is PerfettoCapture
Exception in thread "Thread-1" com.bytedance.rheatrace.processor.core.TraceError: Perfetto return with bad code -1073741515
        at com.bytedance.rheatrace.processor.Main.lambda$main$1(Main.java:81)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.bytedance.rheatrace.processor.core.TraceError: Perfetto return with bad code -1073741515
        at com.bytedance.rheatrace.processor.perfetto.PerfettoCapture.waitForExit(PerfettoCapture.java:89)
        at com.bytedance.rheatrace.processor.Main.lambda$main$1(Main.java:79)
        ... 1 more
10-15 16:51:23.069   RheaTrace : start tracing...
10-15 16:51:28.623   RheaTrace : stop tracing...
10-15 16:51:28.886   RheaTrace : MaxAppTraceBufferSize usage 2241584/500000000 (0%)
10-15 16:51:29.054 E RheaTrace : Error: systrace file not found: rheatrace.workspace\systemTrace.trace
10-15 16:51:29.055 E RheaTrace :  Tips: your device may not support perfetto. please retry with `-mode simple`.

**Comment by WangFeng-AHU** [comment]
看起来像是手机的问题，换个手机或者加上 -mode simple 试试看呢
