### ISSUE TITLE
运行之后没有生成html，存储权限打开了

### ISSUE THREAD

**Issue by renzhenming** [bytedance/btrace#56]
renzhenming@renzhenmingdeMacBook-Air rheatrace % python rheatrace.py -a rhea.sample.android -r -t 5 -o ./output/mynewtrace.html sched freq idle am wm gfx view binder_driver hal dalvik camera input res
2023-02-26 12:07:08,587 - rhea_trace - capture - ERROR: - failed to capture systrace, check your inputs firstly.
2023-02-26 12:07:10,110 - rhea_trace - capture - INFO: - try to force stop rhea.sample.android
2023-02-26 12:07:10,190 - rhea_trace - capture - INFO: - start to launch app rhea.sample.android
2023-02-26 12:07:10,261 - rhea_trace - capture - INFO: - start to capture atrace for 5 seconds, now you can operate your app.
2023-02-26 12:07:15,263 - rhea_trace - capture - INFO: - stop to capture atrace, it maybe take a long time...
2023-02-26 12:07:15,424 - rhea_trace - __init__ - ERROR: - systrace file '/Users/renzhenming/AndroidStudioProjects/btrace-master/scripts/python/rheatrace/output/.build/systrace-origin.html' is not existed.
Traceback (most recent call last):
  File "rheatrace.py", line 310, in <module>
    main_impl(sys.argv)
  File "rheatrace.py", line 270, in main_impl
    trace_processor.processor()
  File "/Users/renzhenming/AndroidStudioProjects/btrace-master/scripts/python/rheatrace/trace_processor.py", line 321, in processor
    result, error_msg = self._standardize_internal()
  File "/Users/renzhenming/AndroidStudioProjects/btrace-master/scripts/python/rheatrace/trace_processor.py", line 183, in _standardize_internal
    self.systrace_origin_lines = open(self.systrace_origin_file, 'rb').readlines()
IOError: [Errno 2] No such file or directory: '/Users/renzhenming/AndroidStudioProjects/btrace-master/scripts/python/rheatrace/output/.build/systrace-origin.html'
renzhenming@renzhenmingdeMacBook-Air rheatrace %

**Comment by mzule** [comment]
> 2023-02-26 12:07:08,587 - rhea_trace - capture - ERROR: - failed to capture systrace, check your inputs firstly.

python 的参数不对，可以先试试用这个命令执行 systrace 会出现什么错误，后续我们会在脚本里面优化一下错误提示。

**Comment by mzule** [comment]
2.0.0 已经不需要存储权限，也不依赖 python了，可以试一下
