### ISSUE TITLE
gson 某些类插桩之后没了导致崩溃还是存在

### ISSUE THREAD

**Issue by liuzhifang1993** [bytedance/btrace#57]
<img width="826" alt="截屏2023-03-01 14 25 04" src="https://user-images.githubusercontent.com/16347830/222061285-f64d9a61-c808-4d1e-93bc-4b3e4bfffb1f.png">

使用的 1.0.2 还是存在这个问题

**Comment by Wan7451** [comment]
相同的问题

**Comment by Wan7451** [comment]
[I][ParseMappingTask] [ParseMappingTask#run] cost:1ms,  collect 0 method from /Users/wan/Documents/WanbaProjects/Android4/android/rhea-trace/keep-method-id.txt
java.util.NoSuchElementException
	at java.base/java.util.zip.ZipFile$ZipEntryIterator.next(ZipFile.java:528)
	at java.base/java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:519)
	at java.base/java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:495)
	at com.bytedance.rheatrace.plugin.compiling.MethodCollector$CollectJarTask.run(MethodCollector.kt:145)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
[E][MethodCollector] Failed to read class:com/google/gson/FieldNamingPolicy$5.class, e:java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.bytedance.rheatrace.plugin.compiling.MethodCollector$TraceClassAdapter.visit, parameter superName
java.util.NoSuchElementException
	at java.base/java.util.zip.ZipFile$ZipEntryIterator.next(ZipFile.java:528)
	at java.base/java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:519)
	at java.base/java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:495)
	at com.bytedance.rheatrace.plugin.compiling.MethodCollector$CollectJarTask.run(MethodCollector.kt:145)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
java.util.NoSuchElementException
	at java.base/java.util.zip.ZipFile$ZipEntryIterator.next(ZipFile.java:528)
	at java.base/java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:519)
	at java.base/java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:495)
	at com.bytedance.rheatrace.plugin.compiling.MethodCollector$CollectJarTask.run(MethodCollector.kt:145)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by Wan7451** [comment]
java.util.NoSuchElementException
	at java.base/java.util.zip.ZipFile$ZipEntryIterator.next(ZipFile.java:528)
	at java.base/java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:519)
	at java.base/java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:495)
	at com.bytedance.rheatrace.plugin.compiling.MethodCollector$CollectJarTask.run(MethodCollector.kt:145)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
[E][MethodCollector] Failed to read class:com/google/gson/FieldNamingPolicy$5.class, e:java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.bytedance.rheatrace.plugin.compiling.MethodCollector$TraceClassAdapter.visit, parameter superName
java.util.NoSuchElementException
	at java.base/java.util.zip.ZipFile$ZipEntryIterator.next(ZipFile.java:528)
	at java.base/java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:519)
	at java.base/java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:495)
	at com.bytedance.rheatrace.plugin.compiling.MethodCollector$CollectJarTask.run(MethodCollector.kt:145)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
java.util.NoSuchElementException
	at java.base/java.util.zip.ZipFile$ZipEntryIterator.next(ZipFile.java:528)
	at java.base/java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:519)
	at java.base/java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:495)
	at com.bytedance.rheatrace.plugin.compiling.MethodCollector$CollectJarTask.run(MethodCollector.kt:145)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by mzule** [comment]
可以试一下最新的 2.0.0 版本
