### ISSUE TITLE
Exception in thread "main" java.net.SocketException: Unexpected end of file from server

### ISSUE THREAD

**Issue by ldw5821cn** [bytedance/btrace#63]
06-26 16:58:09.526   RheaTrace : start tracing...
06-26 16:58:19.845   RheaTrace : stop tracing...
06-26 16:58:20.085   RheaTrace : MaxAppTraceBufferSize usage 4667888/500000000 (0%)
Exception in thread "main" java.net.SocketException: Unexpected end of file from server
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:866)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:863)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1615)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/java.net.URL.openStream(URL.java:1165)
	at org.apache.commons.io.IOUtils.toString(IOUtils.java:2953)
	at com.bytedance.rheatrace.processor.Adb$Http.get(Adb.java:164)
	at com.bytedance.rheatrace.processor.core.Mapping.selectMapping(Mapping.java:47)
	at com.bytedance.rheatrace.processor.core.Mapping.loadMapping(Mapping.java:79)
	at com.bytedance.rheatrace.processor.core.Mapping.get(Mapping.java:36)
	at com.bytedance.rheatrace.processor.core.AppTraceProcessor.processBinary(AppTraceProcessor.java:145)
	at com.bytedance.rheatrace.processor.core.AppTraceProcessor.getBinaryTrace(AppTraceProcessor.java:50)
	at com.bytedance.rheatrace.processor.lite.LiteCapture.process(LiteCapture.java:73)
	at com.bytedance.rheatrace.processor.Main.main(Main.java:108)

›$ adb devices
List of devices attached
66J5T18A15011959        device

**Comment by mzule** [comment]
是不是 needPackageWithMethodMap = false 了？可以通过 -m 参数指定一下 mapping 的路径。
