### ISSUE TITLE
启动崩溃

### ISSUE THREAD

**Issue by renzhenming** [bytedance/btrace#65]
按照文档配置完成，从1.0升级到2.0，应用安装后点击可以正常启动，但是执行命令行开启监控时发生崩溃，报错如下

命令：
java -jar rhea-trace-processor-2.0.0.jar -a sample.tencent.matrix -t 10 -o output.pb -r rhea.all sched -fullClassName

堆栈：
Process: sample.tencent.matrix, PID: 30580
                                                                                                    java.lang.BootstrapMethodError: Exception from call site #1 bootstrap method
                                                                                                    	at com.bytedance.rheatrace.atrace.render.RenderTracer.installInflaterHook(RenderTracer.java:49)
                                                                                                    	at com.bytedance.rheatrace.atrace.render.RenderTracer.onTraceStart(RenderTracer.java:37)
                                                                                                    	at com.bytedance.rheatrace.atrace.RheaATrace.start(RheaATrace.java:86)
                                                                                                    	at com.bytedance.rheatrace.core.TraceSwitch.start(TraceSwitch.java:61)
                                                                                                    	at com.bytedance.rheatrace.core.TraceSwitch.init(TraceSwitch.java:50)
                                                                                                    	at com.bytedance.rheatrace.core.TraceApplicationLike.attachBaseContext(TraceApplicationLike.java:38)
                                                                                                    	at sample.tencent.matrix.MatrixApplication.attachBaseContext(Unknown Source:0)
                                                                                                    	at android.app.Application.attach(Application.java:351)
                                                                                                    	at android.app.Instrumentation.newApplication(Instrumentation.java:1159)
                                                                                                    	at android.app.LoadedApk.makeApplication(LoadedApk.java:1236)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6683)
                                                                                                    	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:223)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7656)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by mzule** [comment]
java -jar rhea-trace-processor-2.0.0.jar -a sample.tencent.matrix -t 10 -o output.pb -r rhea.all sched -fullClassName

**Comment by xinle** [comment]
现在好像还没好
