### ISSUE TITLE
Tips: Please check whether the @CriticalNative annotation is filtered when packaging.

### ISSUE THREAD

**Issue by qiuqifan** [bytedance/btrace#75]
命令：java -jar rhea-trace-processor-2.0.0.jar -a com.xxx.xxx -m methodMapping.txt -t 3 -o output.pb -debug

错误堆栈：
07-04 21:06:41.026 E RheaTrace : Error: Only 0 of the 45620 methods are resolved the method name.
07-04 21:06:41.026 E RheaTrace :  Tips: Please check whether the @CriticalNative annotation is filtered when packaging.
com.bytedance.rheatrace.processor.core.TraceError: Only 0 of the 45620 methods are resolved the method name.
	at com.bytedance.rheatrace.processor.core.AppTraceProcessor.checkNameResolveResult(AppTraceProcessor.java:225)
	at com.bytedance.rheatrace.processor.core.AppTraceProcessor.processBinary(AppTraceProcessor.java:202)
	at com.bytedance.rheatrace.processor.core.AppTraceProcessor.getBinaryTrace(AppTraceProcessor.java:50)
	at com.bytedance.rheatrace.processor.core.AbstractTraceGenerator.getAppTraceFrames(AbstractTraceGenerator.java:39)
	at com.bytedance.rheatrace.processor.core.AbstractTraceGenerator.generate(AbstractTraceGenerator.java:32)
	at com.bytedance.rheatrace.processor.perfetto.PerfettoCapture.process(PerfettoCapture.java:95)
	at com.bytedance.rheatrace.processor.Main.main(Main.java:108)

**Comment by qiuqifan** [comment]
PC环境：macOS 12.4
JDK版本：1.8.0_151

**Comment by Res2013** [comment]
个人遇到的问题，仅供参考：
打开build/outputs/rhea/xxx/methodMapping.txt看下方法id是不是从1开始的，如果不是把needPackageWithMethodMap置为false再抓下Trace看看。

**Comment by mzule** [comment]
@qiuqifan 可以反编译看下 apk 的 com.bytedance.rheatrace.atrace.BinaryTrace 的 nativeBeginMethod 方法有没有 @CriticalNative 注解，如果没有，可以检查下是不是因为一些包体积优化的策略把 @CriticalNative 注解优化掉了。
