### ISSUE TITLE
Caused by: java.lang.UnsupportedOperationException: NestMember requires ASM7

### ISSUE THREAD

**Issue by itcayman** [bytedance/btrace#83]
运行生成apk，插装过程时报错
Caused by: java.lang.UnsupportedOperationException: NestMember requires ASM7
	at org.objectweb.asm.ClassVisitor.visitNestMember(ClassVisitor.java:251)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:696)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
	at com.ss.android.ugc.bytex.common.visitor.ClassVisitorChain.accept(ClassVisitorChain.java:55)
	at com.ss.android.ugc.bytex.common.processor.ClassFileAnalyzer.handle(ClassFileAnalyzer.java:107)
	... 7 more

**Comment by mzule** [comment]
已经发布了一个测试版本，可以验证下 2.0.3-rc01
